/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yaay.backend.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PostChangeAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 223283847535733311L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PostChangeAvro\",\"namespace\":\"com.yaay.backend.model.avro\",\"fields\":[{\"name\":\"userID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"postID\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"postedAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"local-timestamp-millis\"}],\"default\":null},{\"name\":\"operation\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"OperationAvro\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\"]}],\"default\":null},{\"name\":\"hashtag\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"content\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"hasImage\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"hasVideo\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"lat\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"lon\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"category\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.LocalTimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<PostChangeAvro> ENCODER =
      new BinaryMessageEncoder<PostChangeAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PostChangeAvro> DECODER =
      new BinaryMessageDecoder<PostChangeAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PostChangeAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PostChangeAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PostChangeAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PostChangeAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PostChangeAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PostChangeAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PostChangeAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PostChangeAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String userID;
  private java.lang.String postID;
  private java.time.LocalDateTime postedAt;
  private com.yaay.backend.model.avro.OperationAvro operation;
  private java.util.List<java.lang.String> hashtag;
  private java.lang.String content;
  private java.lang.Boolean hasImage;
  private java.lang.Boolean hasVideo;
  private java.lang.Double lat;
  private java.lang.Double lon;
  private java.lang.String category;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PostChangeAvro() {}

  /**
   * All-args constructor.
   * @param userID The new value for userID
   * @param postID The new value for postID
   * @param postedAt The new value for postedAt
   * @param operation The new value for operation
   * @param hashtag The new value for hashtag
   * @param content The new value for content
   * @param hasImage The new value for hasImage
   * @param hasVideo The new value for hasVideo
   * @param lat The new value for lat
   * @param lon The new value for lon
   * @param category The new value for category
   */
  public PostChangeAvro(java.lang.String userID, java.lang.String postID, java.time.LocalDateTime postedAt, com.yaay.backend.model.avro.OperationAvro operation, java.util.List<java.lang.String> hashtag, java.lang.String content, java.lang.Boolean hasImage, java.lang.Boolean hasVideo, java.lang.Double lat, java.lang.Double lon, java.lang.String category) {
    this.userID = userID;
    this.postID = postID;
    this.postedAt = postedAt;
    this.operation = operation;
    this.hashtag = hashtag;
    this.content = content;
    this.hasImage = hasImage;
    this.hasVideo = hasVideo;
    this.lat = lat;
    this.lon = lon;
    this.category = category;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userID;
    case 1: return postID;
    case 2: return postedAt;
    case 3: return operation;
    case 4: return hashtag;
    case 5: return content;
    case 6: return hasImage;
    case 7: return hasVideo;
    case 8: return lat;
    case 9: return lon;
    case 10: return category;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userID = value$ != null ? value$.toString() : null; break;
    case 1: postID = value$ != null ? value$.toString() : null; break;
    case 2: postedAt = (java.time.LocalDateTime)value$; break;
    case 3: operation = (com.yaay.backend.model.avro.OperationAvro)value$; break;
    case 4: hashtag = (java.util.List<java.lang.String>)value$; break;
    case 5: content = value$ != null ? value$.toString() : null; break;
    case 6: hasImage = (java.lang.Boolean)value$; break;
    case 7: hasVideo = (java.lang.Boolean)value$; break;
    case 8: lat = (java.lang.Double)value$; break;
    case 9: lon = (java.lang.Double)value$; break;
    case 10: category = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userID' field.
   * @return The value of the 'userID' field.
   */
  public java.lang.String getUserID() {
    return userID;
  }


  /**
   * Sets the value of the 'userID' field.
   * @param value the value to set.
   */
  public void setUserID(java.lang.String value) {
    this.userID = value;
  }

  /**
   * Gets the value of the 'postID' field.
   * @return The value of the 'postID' field.
   */
  public java.lang.String getPostID() {
    return postID;
  }


  /**
   * Sets the value of the 'postID' field.
   * @param value the value to set.
   */
  public void setPostID(java.lang.String value) {
    this.postID = value;
  }

  /**
   * Gets the value of the 'postedAt' field.
   * @return The value of the 'postedAt' field.
   */
  public java.time.LocalDateTime getPostedAt() {
    return postedAt;
  }


  /**
   * Sets the value of the 'postedAt' field.
   * @param value the value to set.
   */
  public void setPostedAt(java.time.LocalDateTime value) {
    this.postedAt = value;
  }

  /**
   * Gets the value of the 'operation' field.
   * @return The value of the 'operation' field.
   */
  public com.yaay.backend.model.avro.OperationAvro getOperation() {
    return operation;
  }


  /**
   * Sets the value of the 'operation' field.
   * @param value the value to set.
   */
  public void setOperation(com.yaay.backend.model.avro.OperationAvro value) {
    this.operation = value;
  }

  /**
   * Gets the value of the 'hashtag' field.
   * @return The value of the 'hashtag' field.
   */
  public java.util.List<java.lang.String> getHashtag() {
    return hashtag;
  }


  /**
   * Sets the value of the 'hashtag' field.
   * @param value the value to set.
   */
  public void setHashtag(java.util.List<java.lang.String> value) {
    this.hashtag = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.String getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.String value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'hasImage' field.
   * @return The value of the 'hasImage' field.
   */
  public java.lang.Boolean getHasImage() {
    return hasImage;
  }


  /**
   * Sets the value of the 'hasImage' field.
   * @param value the value to set.
   */
  public void setHasImage(java.lang.Boolean value) {
    this.hasImage = value;
  }

  /**
   * Gets the value of the 'hasVideo' field.
   * @return The value of the 'hasVideo' field.
   */
  public java.lang.Boolean getHasVideo() {
    return hasVideo;
  }


  /**
   * Sets the value of the 'hasVideo' field.
   * @param value the value to set.
   */
  public void setHasVideo(java.lang.Boolean value) {
    this.hasVideo = value;
  }

  /**
   * Gets the value of the 'lat' field.
   * @return The value of the 'lat' field.
   */
  public java.lang.Double getLat() {
    return lat;
  }


  /**
   * Sets the value of the 'lat' field.
   * @param value the value to set.
   */
  public void setLat(java.lang.Double value) {
    this.lat = value;
  }

  /**
   * Gets the value of the 'lon' field.
   * @return The value of the 'lon' field.
   */
  public java.lang.Double getLon() {
    return lon;
  }


  /**
   * Sets the value of the 'lon' field.
   * @param value the value to set.
   */
  public void setLon(java.lang.Double value) {
    this.lon = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public java.lang.String getCategory() {
    return category;
  }


  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(java.lang.String value) {
    this.category = value;
  }

  /**
   * Creates a new PostChangeAvro RecordBuilder.
   * @return A new PostChangeAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.PostChangeAvro.Builder newBuilder() {
    return new com.yaay.backend.model.avro.PostChangeAvro.Builder();
  }

  /**
   * Creates a new PostChangeAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PostChangeAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.PostChangeAvro.Builder newBuilder(com.yaay.backend.model.avro.PostChangeAvro.Builder other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.PostChangeAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.PostChangeAvro.Builder(other);
    }
  }

  /**
   * Creates a new PostChangeAvro RecordBuilder by copying an existing PostChangeAvro instance.
   * @param other The existing instance to copy.
   * @return A new PostChangeAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.PostChangeAvro.Builder newBuilder(com.yaay.backend.model.avro.PostChangeAvro other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.PostChangeAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.PostChangeAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for PostChangeAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PostChangeAvro>
    implements org.apache.avro.data.RecordBuilder<PostChangeAvro> {

    private java.lang.String userID;
    private java.lang.String postID;
    private java.time.LocalDateTime postedAt;
    private com.yaay.backend.model.avro.OperationAvro operation;
    private java.util.List<java.lang.String> hashtag;
    private java.lang.String content;
    private java.lang.Boolean hasImage;
    private java.lang.Boolean hasVideo;
    private java.lang.Double lat;
    private java.lang.Double lon;
    private java.lang.String category;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yaay.backend.model.avro.PostChangeAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userID)) {
        this.userID = data().deepCopy(fields()[0].schema(), other.userID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.postID)) {
        this.postID = data().deepCopy(fields()[1].schema(), other.postID);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.postedAt)) {
        this.postedAt = data().deepCopy(fields()[2].schema(), other.postedAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.operation)) {
        this.operation = data().deepCopy(fields()[3].schema(), other.operation);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.hashtag)) {
        this.hashtag = data().deepCopy(fields()[4].schema(), other.hashtag);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.content)) {
        this.content = data().deepCopy(fields()[5].schema(), other.content);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.hasImage)) {
        this.hasImage = data().deepCopy(fields()[6].schema(), other.hasImage);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.hasVideo)) {
        this.hasVideo = data().deepCopy(fields()[7].schema(), other.hasVideo);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.lat)) {
        this.lat = data().deepCopy(fields()[8].schema(), other.lat);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.lon)) {
        this.lon = data().deepCopy(fields()[9].schema(), other.lon);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.category)) {
        this.category = data().deepCopy(fields()[10].schema(), other.category);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing PostChangeAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yaay.backend.model.avro.PostChangeAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userID)) {
        this.userID = data().deepCopy(fields()[0].schema(), other.userID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.postID)) {
        this.postID = data().deepCopy(fields()[1].schema(), other.postID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.postedAt)) {
        this.postedAt = data().deepCopy(fields()[2].schema(), other.postedAt);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.operation)) {
        this.operation = data().deepCopy(fields()[3].schema(), other.operation);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.hashtag)) {
        this.hashtag = data().deepCopy(fields()[4].schema(), other.hashtag);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.content)) {
        this.content = data().deepCopy(fields()[5].schema(), other.content);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.hasImage)) {
        this.hasImage = data().deepCopy(fields()[6].schema(), other.hasImage);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.hasVideo)) {
        this.hasVideo = data().deepCopy(fields()[7].schema(), other.hasVideo);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lat)) {
        this.lat = data().deepCopy(fields()[8].schema(), other.lat);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.lon)) {
        this.lon = data().deepCopy(fields()[9].schema(), other.lon);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.category)) {
        this.category = data().deepCopy(fields()[10].schema(), other.category);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'userID' field.
      * @return The value.
      */
    public java.lang.String getUserID() {
      return userID;
    }


    /**
      * Sets the value of the 'userID' field.
      * @param value The value of 'userID'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setUserID(java.lang.String value) {
      validate(fields()[0], value);
      this.userID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userID' field has been set.
      * @return True if the 'userID' field has been set, false otherwise.
      */
    public boolean hasUserID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userID' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearUserID() {
      userID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'postID' field.
      * @return The value.
      */
    public java.lang.String getPostID() {
      return postID;
    }


    /**
      * Sets the value of the 'postID' field.
      * @param value The value of 'postID'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setPostID(java.lang.String value) {
      validate(fields()[1], value);
      this.postID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'postID' field has been set.
      * @return True if the 'postID' field has been set, false otherwise.
      */
    public boolean hasPostID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'postID' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearPostID() {
      postID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'postedAt' field.
      * @return The value.
      */
    public java.time.LocalDateTime getPostedAt() {
      return postedAt;
    }


    /**
      * Sets the value of the 'postedAt' field.
      * @param value The value of 'postedAt'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setPostedAt(java.time.LocalDateTime value) {
      validate(fields()[2], value);
      this.postedAt = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'postedAt' field has been set.
      * @return True if the 'postedAt' field has been set, false otherwise.
      */
    public boolean hasPostedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'postedAt' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearPostedAt() {
      postedAt = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'operation' field.
      * @return The value.
      */
    public com.yaay.backend.model.avro.OperationAvro getOperation() {
      return operation;
    }


    /**
      * Sets the value of the 'operation' field.
      * @param value The value of 'operation'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setOperation(com.yaay.backend.model.avro.OperationAvro value) {
      validate(fields()[3], value);
      this.operation = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'operation' field has been set.
      * @return True if the 'operation' field has been set, false otherwise.
      */
    public boolean hasOperation() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'operation' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearOperation() {
      operation = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'hashtag' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getHashtag() {
      return hashtag;
    }


    /**
      * Sets the value of the 'hashtag' field.
      * @param value The value of 'hashtag'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setHashtag(java.util.List<java.lang.String> value) {
      validate(fields()[4], value);
      this.hashtag = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'hashtag' field has been set.
      * @return True if the 'hashtag' field has been set, false otherwise.
      */
    public boolean hasHashtag() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'hashtag' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearHashtag() {
      hashtag = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.String getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setContent(java.lang.String value) {
      validate(fields()[5], value);
      this.content = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearContent() {
      content = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'hasImage' field.
      * @return The value.
      */
    public java.lang.Boolean getHasImage() {
      return hasImage;
    }


    /**
      * Sets the value of the 'hasImage' field.
      * @param value The value of 'hasImage'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setHasImage(java.lang.Boolean value) {
      validate(fields()[6], value);
      this.hasImage = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'hasImage' field has been set.
      * @return True if the 'hasImage' field has been set, false otherwise.
      */
    public boolean hasHasImage() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'hasImage' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearHasImage() {
      hasImage = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'hasVideo' field.
      * @return The value.
      */
    public java.lang.Boolean getHasVideo() {
      return hasVideo;
    }


    /**
      * Sets the value of the 'hasVideo' field.
      * @param value The value of 'hasVideo'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setHasVideo(java.lang.Boolean value) {
      validate(fields()[7], value);
      this.hasVideo = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'hasVideo' field has been set.
      * @return True if the 'hasVideo' field has been set, false otherwise.
      */
    public boolean hasHasVideo() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'hasVideo' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearHasVideo() {
      hasVideo = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'lat' field.
      * @return The value.
      */
    public java.lang.Double getLat() {
      return lat;
    }


    /**
      * Sets the value of the 'lat' field.
      * @param value The value of 'lat'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setLat(java.lang.Double value) {
      validate(fields()[8], value);
      this.lat = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'lat' field has been set.
      * @return True if the 'lat' field has been set, false otherwise.
      */
    public boolean hasLat() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'lat' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearLat() {
      lat = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'lon' field.
      * @return The value.
      */
    public java.lang.Double getLon() {
      return lon;
    }


    /**
      * Sets the value of the 'lon' field.
      * @param value The value of 'lon'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setLon(java.lang.Double value) {
      validate(fields()[9], value);
      this.lon = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'lon' field has been set.
      * @return True if the 'lon' field has been set, false otherwise.
      */
    public boolean hasLon() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'lon' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearLon() {
      lon = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public java.lang.String getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder setCategory(java.lang.String value) {
      validate(fields()[10], value);
      this.category = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.PostChangeAvro.Builder clearCategory() {
      category = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PostChangeAvro build() {
      try {
        PostChangeAvro record = new PostChangeAvro();
        record.userID = fieldSetFlags()[0] ? this.userID : (java.lang.String) defaultValue(fields()[0]);
        record.postID = fieldSetFlags()[1] ? this.postID : (java.lang.String) defaultValue(fields()[1]);
        record.postedAt = fieldSetFlags()[2] ? this.postedAt : (java.time.LocalDateTime) defaultValue(fields()[2]);
        record.operation = fieldSetFlags()[3] ? this.operation : (com.yaay.backend.model.avro.OperationAvro) defaultValue(fields()[3]);
        record.hashtag = fieldSetFlags()[4] ? this.hashtag : (java.util.List<java.lang.String>) defaultValue(fields()[4]);
        record.content = fieldSetFlags()[5] ? this.content : (java.lang.String) defaultValue(fields()[5]);
        record.hasImage = fieldSetFlags()[6] ? this.hasImage : (java.lang.Boolean) defaultValue(fields()[6]);
        record.hasVideo = fieldSetFlags()[7] ? this.hasVideo : (java.lang.Boolean) defaultValue(fields()[7]);
        record.lat = fieldSetFlags()[8] ? this.lat : (java.lang.Double) defaultValue(fields()[8]);
        record.lon = fieldSetFlags()[9] ? this.lon : (java.lang.Double) defaultValue(fields()[9]);
        record.category = fieldSetFlags()[10] ? this.category : (java.lang.String) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PostChangeAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<PostChangeAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PostChangeAvro>
    READER$ = (org.apache.avro.io.DatumReader<PostChangeAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










