/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yaay.backend.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum QueryAvro implements org.apache.avro.generic.GenericEnumSymbol<QueryAvro> {
  MUTED, MUTED_BY, FOLLOWERS, FOLLOWING, BLOCKED, BLOCKED_BY, WHITELISTED_FOLLOWERS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"QueryAvro\",\"namespace\":\"com.yaay.backend.model.avro\",\"symbols\":[\"MUTED\",\"MUTED_BY\",\"FOLLOWERS\",\"FOLLOWING\",\"BLOCKED\",\"BLOCKED_BY\",\"WHITELISTED_FOLLOWERS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
