/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yaay.backend.model.avro;
@org.apache.avro.specific.AvroGenerated
public enum RelationAvro implements org.apache.avro.generic.GenericEnumSymbol<RelationAvro> {
  MUTED, FOLLOWS, BLOCKED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RelationAvro\",\"namespace\":\"com.yaay.backend.model.avro\",\"symbols\":[\"MUTED\",\"FOLLOWS\",\"BLOCKED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
