/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yaay.backend.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RelationChangeRequestAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 342503134269994165L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RelationChangeRequestAvro\",\"namespace\":\"com.yaay.backend.model.avro\",\"fields\":[{\"name\":\"sourceUserId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"targetUserId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RelationChangeRequestAvro> ENCODER =
      new BinaryMessageEncoder<RelationChangeRequestAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RelationChangeRequestAvro> DECODER =
      new BinaryMessageDecoder<RelationChangeRequestAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RelationChangeRequestAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RelationChangeRequestAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RelationChangeRequestAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RelationChangeRequestAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RelationChangeRequestAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RelationChangeRequestAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RelationChangeRequestAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RelationChangeRequestAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String sourceUserId;
  private java.lang.String targetUserId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RelationChangeRequestAvro() {}

  /**
   * All-args constructor.
   * @param sourceUserId The new value for sourceUserId
   * @param targetUserId The new value for targetUserId
   */
  public RelationChangeRequestAvro(java.lang.String sourceUserId, java.lang.String targetUserId) {
    this.sourceUserId = sourceUserId;
    this.targetUserId = targetUserId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sourceUserId;
    case 1: return targetUserId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sourceUserId = value$ != null ? value$.toString() : null; break;
    case 1: targetUserId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sourceUserId' field.
   * @return The value of the 'sourceUserId' field.
   */
  public java.lang.String getSourceUserId() {
    return sourceUserId;
  }


  /**
   * Sets the value of the 'sourceUserId' field.
   * @param value the value to set.
   */
  public void setSourceUserId(java.lang.String value) {
    this.sourceUserId = value;
  }

  /**
   * Gets the value of the 'targetUserId' field.
   * @return The value of the 'targetUserId' field.
   */
  public java.lang.String getTargetUserId() {
    return targetUserId;
  }


  /**
   * Sets the value of the 'targetUserId' field.
   * @param value the value to set.
   */
  public void setTargetUserId(java.lang.String value) {
    this.targetUserId = value;
  }

  /**
   * Creates a new RelationChangeRequestAvro RecordBuilder.
   * @return A new RelationChangeRequestAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder newBuilder() {
    return new com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder();
  }

  /**
   * Creates a new RelationChangeRequestAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RelationChangeRequestAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder newBuilder(com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder(other);
    }
  }

  /**
   * Creates a new RelationChangeRequestAvro RecordBuilder by copying an existing RelationChangeRequestAvro instance.
   * @param other The existing instance to copy.
   * @return A new RelationChangeRequestAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder newBuilder(com.yaay.backend.model.avro.RelationChangeRequestAvro other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for RelationChangeRequestAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RelationChangeRequestAvro>
    implements org.apache.avro.data.RecordBuilder<RelationChangeRequestAvro> {

    private java.lang.String sourceUserId;
    private java.lang.String targetUserId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sourceUserId)) {
        this.sourceUserId = data().deepCopy(fields()[0].schema(), other.sourceUserId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.targetUserId)) {
        this.targetUserId = data().deepCopy(fields()[1].schema(), other.targetUserId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing RelationChangeRequestAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yaay.backend.model.avro.RelationChangeRequestAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sourceUserId)) {
        this.sourceUserId = data().deepCopy(fields()[0].schema(), other.sourceUserId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.targetUserId)) {
        this.targetUserId = data().deepCopy(fields()[1].schema(), other.targetUserId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sourceUserId' field.
      * @return The value.
      */
    public java.lang.String getSourceUserId() {
      return sourceUserId;
    }


    /**
      * Sets the value of the 'sourceUserId' field.
      * @param value The value of 'sourceUserId'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder setSourceUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.sourceUserId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sourceUserId' field has been set.
      * @return True if the 'sourceUserId' field has been set, false otherwise.
      */
    public boolean hasSourceUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sourceUserId' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder clearSourceUserId() {
      sourceUserId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'targetUserId' field.
      * @return The value.
      */
    public java.lang.String getTargetUserId() {
      return targetUserId;
    }


    /**
      * Sets the value of the 'targetUserId' field.
      * @param value The value of 'targetUserId'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder setTargetUserId(java.lang.String value) {
      validate(fields()[1], value);
      this.targetUserId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'targetUserId' field has been set.
      * @return True if the 'targetUserId' field has been set, false otherwise.
      */
    public boolean hasTargetUserId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'targetUserId' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelationChangeRequestAvro.Builder clearTargetUserId() {
      targetUserId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RelationChangeRequestAvro build() {
      try {
        RelationChangeRequestAvro record = new RelationChangeRequestAvro();
        record.sourceUserId = fieldSetFlags()[0] ? this.sourceUserId : (java.lang.String) defaultValue(fields()[0]);
        record.targetUserId = fieldSetFlags()[1] ? this.targetUserId : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RelationChangeRequestAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<RelationChangeRequestAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RelationChangeRequestAvro>
    READER$ = (org.apache.avro.io.DatumReader<RelationChangeRequestAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.sourceUserId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.sourceUserId);
    }

    if (this.targetUserId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.targetUserId);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.sourceUserId = null;
      } else {
        this.sourceUserId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.targetUserId = null;
      } else {
        this.targetUserId = in.readString();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sourceUserId = null;
          } else {
            this.sourceUserId = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.targetUserId = null;
          } else {
            this.targetUserId = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










