/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yaay.backend.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RelevancyResponseAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2382958489697451715L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RelevancyResponseAvro\",\"namespace\":\"com.yaay.backend.model.avro\",\"fields\":[{\"name\":\"size\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"pagingState\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"elements\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"UserDTOAvro\",\"fields\":[{\"name\":\"userId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"since\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<RelevancyResponseAvro> ENCODER =
      new BinaryMessageEncoder<RelevancyResponseAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RelevancyResponseAvro> DECODER =
      new BinaryMessageDecoder<RelevancyResponseAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RelevancyResponseAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RelevancyResponseAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RelevancyResponseAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RelevancyResponseAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RelevancyResponseAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RelevancyResponseAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RelevancyResponseAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RelevancyResponseAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.Integer size;
  private java.lang.String pagingState;
  private java.util.List<com.yaay.backend.model.avro.UserDTOAvro> elements;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RelevancyResponseAvro() {}

  /**
   * All-args constructor.
   * @param size The new value for size
   * @param pagingState The new value for pagingState
   * @param elements The new value for elements
   */
  public RelevancyResponseAvro(java.lang.Integer size, java.lang.String pagingState, java.util.List<com.yaay.backend.model.avro.UserDTOAvro> elements) {
    this.size = size;
    this.pagingState = pagingState;
    this.elements = elements;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return size;
    case 1: return pagingState;
    case 2: return elements;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: size = (java.lang.Integer)value$; break;
    case 1: pagingState = value$ != null ? value$.toString() : null; break;
    case 2: elements = (java.util.List<com.yaay.backend.model.avro.UserDTOAvro>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'size' field.
   * @return The value of the 'size' field.
   */
  public java.lang.Integer getSize() {
    return size;
  }


  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(java.lang.Integer value) {
    this.size = value;
  }

  /**
   * Gets the value of the 'pagingState' field.
   * @return The value of the 'pagingState' field.
   */
  public java.lang.String getPagingState() {
    return pagingState;
  }


  /**
   * Sets the value of the 'pagingState' field.
   * @param value the value to set.
   */
  public void setPagingState(java.lang.String value) {
    this.pagingState = value;
  }

  /**
   * Gets the value of the 'elements' field.
   * @return The value of the 'elements' field.
   */
  public java.util.List<com.yaay.backend.model.avro.UserDTOAvro> getElements() {
    return elements;
  }


  /**
   * Sets the value of the 'elements' field.
   * @param value the value to set.
   */
  public void setElements(java.util.List<com.yaay.backend.model.avro.UserDTOAvro> value) {
    this.elements = value;
  }

  /**
   * Creates a new RelevancyResponseAvro RecordBuilder.
   * @return A new RelevancyResponseAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelevancyResponseAvro.Builder newBuilder() {
    return new com.yaay.backend.model.avro.RelevancyResponseAvro.Builder();
  }

  /**
   * Creates a new RelevancyResponseAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RelevancyResponseAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelevancyResponseAvro.Builder newBuilder(com.yaay.backend.model.avro.RelevancyResponseAvro.Builder other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.RelevancyResponseAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.RelevancyResponseAvro.Builder(other);
    }
  }

  /**
   * Creates a new RelevancyResponseAvro RecordBuilder by copying an existing RelevancyResponseAvro instance.
   * @param other The existing instance to copy.
   * @return A new RelevancyResponseAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelevancyResponseAvro.Builder newBuilder(com.yaay.backend.model.avro.RelevancyResponseAvro other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.RelevancyResponseAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.RelevancyResponseAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for RelevancyResponseAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RelevancyResponseAvro>
    implements org.apache.avro.data.RecordBuilder<RelevancyResponseAvro> {

    private java.lang.Integer size;
    private java.lang.String pagingState;
    private java.util.List<com.yaay.backend.model.avro.UserDTOAvro> elements;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yaay.backend.model.avro.RelevancyResponseAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.size)) {
        this.size = data().deepCopy(fields()[0].schema(), other.size);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.pagingState)) {
        this.pagingState = data().deepCopy(fields()[1].schema(), other.pagingState);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.elements)) {
        this.elements = data().deepCopy(fields()[2].schema(), other.elements);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RelevancyResponseAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yaay.backend.model.avro.RelevancyResponseAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.size)) {
        this.size = data().deepCopy(fields()[0].schema(), other.size);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pagingState)) {
        this.pagingState = data().deepCopy(fields()[1].schema(), other.pagingState);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.elements)) {
        this.elements = data().deepCopy(fields()[2].schema(), other.elements);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'size' field.
      * @return The value.
      */
    public java.lang.Integer getSize() {
      return size;
    }


    /**
      * Sets the value of the 'size' field.
      * @param value The value of 'size'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyResponseAvro.Builder setSize(java.lang.Integer value) {
      validate(fields()[0], value);
      this.size = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'size' field has been set.
      * @return True if the 'size' field has been set, false otherwise.
      */
    public boolean hasSize() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'size' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyResponseAvro.Builder clearSize() {
      size = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'pagingState' field.
      * @return The value.
      */
    public java.lang.String getPagingState() {
      return pagingState;
    }


    /**
      * Sets the value of the 'pagingState' field.
      * @param value The value of 'pagingState'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyResponseAvro.Builder setPagingState(java.lang.String value) {
      validate(fields()[1], value);
      this.pagingState = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'pagingState' field has been set.
      * @return True if the 'pagingState' field has been set, false otherwise.
      */
    public boolean hasPagingState() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'pagingState' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyResponseAvro.Builder clearPagingState() {
      pagingState = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'elements' field.
      * @return The value.
      */
    public java.util.List<com.yaay.backend.model.avro.UserDTOAvro> getElements() {
      return elements;
    }


    /**
      * Sets the value of the 'elements' field.
      * @param value The value of 'elements'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyResponseAvro.Builder setElements(java.util.List<com.yaay.backend.model.avro.UserDTOAvro> value) {
      validate(fields()[2], value);
      this.elements = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'elements' field has been set.
      * @return True if the 'elements' field has been set, false otherwise.
      */
    public boolean hasElements() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'elements' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyResponseAvro.Builder clearElements() {
      elements = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RelevancyResponseAvro build() {
      try {
        RelevancyResponseAvro record = new RelevancyResponseAvro();
        record.size = fieldSetFlags()[0] ? this.size : (java.lang.Integer) defaultValue(fields()[0]);
        record.pagingState = fieldSetFlags()[1] ? this.pagingState : (java.lang.String) defaultValue(fields()[1]);
        record.elements = fieldSetFlags()[2] ? this.elements : (java.util.List<com.yaay.backend.model.avro.UserDTOAvro>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RelevancyResponseAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<RelevancyResponseAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RelevancyResponseAvro>
    READER$ = (org.apache.avro.io.DatumReader<RelevancyResponseAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










