/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.yaay.backend.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RelevancyRequestAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2300968259477217966L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RelevancyRequestAvro\",\"namespace\":\"com.yaay.backend.model.avro\",\"fields\":[{\"name\":\"userId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"pagingState\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"limit\",\"type\":[\"null\",\"int\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RelevancyRequestAvro> ENCODER =
      new BinaryMessageEncoder<RelevancyRequestAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RelevancyRequestAvro> DECODER =
      new BinaryMessageDecoder<RelevancyRequestAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RelevancyRequestAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RelevancyRequestAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RelevancyRequestAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RelevancyRequestAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RelevancyRequestAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RelevancyRequestAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RelevancyRequestAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RelevancyRequestAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String userId;
  private java.lang.String pagingState;
  private java.lang.Integer limit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RelevancyRequestAvro() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param pagingState The new value for pagingState
   * @param limit The new value for limit
   */
  public RelevancyRequestAvro(java.lang.String userId, java.lang.String pagingState, java.lang.Integer limit) {
    this.userId = userId;
    this.pagingState = pagingState;
    this.limit = limit;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return pagingState;
    case 2: return limit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = value$ != null ? value$.toString() : null; break;
    case 1: pagingState = value$ != null ? value$.toString() : null; break;
    case 2: limit = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'pagingState' field.
   * @return The value of the 'pagingState' field.
   */
  public java.lang.String getPagingState() {
    return pagingState;
  }


  /**
   * Sets the value of the 'pagingState' field.
   * @param value the value to set.
   */
  public void setPagingState(java.lang.String value) {
    this.pagingState = value;
  }

  /**
   * Gets the value of the 'limit' field.
   * @return The value of the 'limit' field.
   */
  public java.lang.Integer getLimit() {
    return limit;
  }


  /**
   * Sets the value of the 'limit' field.
   * @param value the value to set.
   */
  public void setLimit(java.lang.Integer value) {
    this.limit = value;
  }

  /**
   * Creates a new RelevancyRequestAvro RecordBuilder.
   * @return A new RelevancyRequestAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelevancyRequestAvro.Builder newBuilder() {
    return new com.yaay.backend.model.avro.RelevancyRequestAvro.Builder();
  }

  /**
   * Creates a new RelevancyRequestAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RelevancyRequestAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelevancyRequestAvro.Builder newBuilder(com.yaay.backend.model.avro.RelevancyRequestAvro.Builder other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.RelevancyRequestAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.RelevancyRequestAvro.Builder(other);
    }
  }

  /**
   * Creates a new RelevancyRequestAvro RecordBuilder by copying an existing RelevancyRequestAvro instance.
   * @param other The existing instance to copy.
   * @return A new RelevancyRequestAvro RecordBuilder
   */
  public static com.yaay.backend.model.avro.RelevancyRequestAvro.Builder newBuilder(com.yaay.backend.model.avro.RelevancyRequestAvro other) {
    if (other == null) {
      return new com.yaay.backend.model.avro.RelevancyRequestAvro.Builder();
    } else {
      return new com.yaay.backend.model.avro.RelevancyRequestAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for RelevancyRequestAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RelevancyRequestAvro>
    implements org.apache.avro.data.RecordBuilder<RelevancyRequestAvro> {

    private java.lang.String userId;
    private java.lang.String pagingState;
    private java.lang.Integer limit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.yaay.backend.model.avro.RelevancyRequestAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.pagingState)) {
        this.pagingState = data().deepCopy(fields()[1].schema(), other.pagingState);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.limit)) {
        this.limit = data().deepCopy(fields()[2].schema(), other.limit);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing RelevancyRequestAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.yaay.backend.model.avro.RelevancyRequestAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pagingState)) {
        this.pagingState = data().deepCopy(fields()[1].schema(), other.pagingState);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.limit)) {
        this.limit = data().deepCopy(fields()[2].schema(), other.limit);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyRequestAvro.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyRequestAvro.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'pagingState' field.
      * @return The value.
      */
    public java.lang.String getPagingState() {
      return pagingState;
    }


    /**
      * Sets the value of the 'pagingState' field.
      * @param value The value of 'pagingState'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyRequestAvro.Builder setPagingState(java.lang.String value) {
      validate(fields()[1], value);
      this.pagingState = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'pagingState' field has been set.
      * @return True if the 'pagingState' field has been set, false otherwise.
      */
    public boolean hasPagingState() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'pagingState' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyRequestAvro.Builder clearPagingState() {
      pagingState = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'limit' field.
      * @return The value.
      */
    public java.lang.Integer getLimit() {
      return limit;
    }


    /**
      * Sets the value of the 'limit' field.
      * @param value The value of 'limit'.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyRequestAvro.Builder setLimit(java.lang.Integer value) {
      validate(fields()[2], value);
      this.limit = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'limit' field has been set.
      * @return True if the 'limit' field has been set, false otherwise.
      */
    public boolean hasLimit() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'limit' field.
      * @return This builder.
      */
    public com.yaay.backend.model.avro.RelevancyRequestAvro.Builder clearLimit() {
      limit = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RelevancyRequestAvro build() {
      try {
        RelevancyRequestAvro record = new RelevancyRequestAvro();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.String) defaultValue(fields()[0]);
        record.pagingState = fieldSetFlags()[1] ? this.pagingState : (java.lang.String) defaultValue(fields()[1]);
        record.limit = fieldSetFlags()[2] ? this.limit : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RelevancyRequestAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<RelevancyRequestAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RelevancyRequestAvro>
    READER$ = (org.apache.avro.io.DatumReader<RelevancyRequestAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.userId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.userId);
    }

    if (this.pagingState == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.pagingState);
    }

    if (this.limit == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.limit);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.userId = null;
      } else {
        this.userId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.pagingState = null;
      } else {
        this.pagingState = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.limit = null;
      } else {
        this.limit = in.readInt();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.userId = null;
          } else {
            this.userId = in.readString();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.pagingState = null;
          } else {
            this.pagingState = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.limit = null;
          } else {
            this.limit = in.readInt();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










